### ISSUE TITLE
PPTT table

### ISSUE THREAD

**Issue by andreiw** [pftf/RPi4#10]
We have a proposed PPTT table now (attached) from Jeremy. It just needs to show up in some future release.
[0001-platform-rp4-acpi-Add-PPTT.patch.txt](https://github.com/pftf/RPi4/files/4272425/0001-platform-rp4-acpi-Add-PPTT.patch.txt)

**Comment by jlinton** [comment]
I've created a pull request https://github.com/pftf/edk2-platforms/pull/11

**Comment by pbatard** [comment]
Submitted for review in https://edk2.groups.io/g/devel/message/56407.

**Comment by pbatard** [comment]
Fixed in v1.7
