### ISSUE TITLE
RPi4 PMU GSIV in GICC should be SPI, not PPI

### ISSUE THREAD

**Issue by shiriyuru** [pftf/RPi4#103]
The PMU GSIV value in RPi4 was changed to PPI 23 for ACS compliance testing for SBSA.
https://github.com/tianocore/edk2-platforms/commit/602a7ea1ab6d0a84c48981911f61067c20fb0a5a
But overflow interrupt on the GICv2 system is actually wired as SPI, not PPI.

**Comment by samerhaj** [comment]
According to the reference linux DT:
https://github.com/raspberrypi/linux/blob/rpi-5.4.y/arch/arm/boot/dts/bcm2711.dtsi#L274 pmu interrupt is not PPI, it’s SPI.

**Comment by pbatard** [comment]
This should be fixed with UEFI firmware v1.22.
