### ISSUE TITLE
Sychronous Excepetion at 0x00000000371013F4

### ISSUE THREAD

**Issue by einsteinagogo** [pftf/RPi4#104]
Seem to be getting quite a few Sychronous Excepetion at 0x00000000371013F4 on Pi4 8GB with latest EEPROM from Sept 2020.

**Comment by einsteinagogo** [comment]
Seem to be getting quite a few Sychronous Excepetion at 0x00000000371013F4 on Pi4 8GB with latest EEPROM from Sept 2020.

**Comment by andreiw** [comment]
Duplicate of https://github.com/pftf/RPi4/issues/97

**Comment by andreiw** [comment]
Thanks for your report. It's not related to iSCSI config, but it is related to persisting UEFI config to SD card.

**Comment by andreiw** [comment]
Duplicate for https://github.com/pftf/RPi4/issues/97
