### ISSUE TITLE
iSCSI option / re-enable feature request

### ISSUE THREAD

**Issue by ppapajohn** [pftf/RPi4#139]
Hi all, 

first of all congrats on the amazing stuff you are performing. :) 

Would it be possible to re-enable the iSCSI boot option in v1.23? Without taking too much of your time, I have an rpi4 8GB, and a Synology to serve as an iSCSI server. I intentionally use UEFI firmware v1.21, in order to boot from iSCSI. This firmware throws synchronous exceptions, which are solved in v1.22. The latter though does not allow for iSCSI boot option.

In advance thank you very much for your time and consideration on my request. 

Best Regards,
Panos

**Comment by ppapajohn** [comment]
Hi all,
Sorry for missing that you have added back the iSCSI option in v1.24. Please close this feature request, delete it, whatever you deem most appropriate.

Thank you and sorry for the hustle; I was dizzy I guess. 🙂 

Best Regards,
Panos

**Comment by samerhaj** [comment]
Closing as fixed in 1.24
