### ISSUE TITLE
Some problems encountered when using UEFI

### ISSUE THREAD

**Issue by Nitric-acid-CN** [pftf/RPi4#142]
I met a problem while I'm starting Window 10 arm(And I'm using USB drive):
`Windows Boot Manager
Windows failed to start. A recent hardware or software change might be the cause. 
To fix the problem:
1. Insert your Windows installation disc and restart your computer
2. Choose your language settings, and then click "Next."
3. CIick "Repair your computer .”
If you do not have this disc, contact your systen administrator or computer manufacturer for assistance .
File: \EFI\Microsoft\Boot\BCD
Status: 0xc0000225
Info: The Boot Configuration Data for your PC is missing or contains errors.
ESC UEFI Firmware Settings`

**Comment by samerhaj** [comment]
This has been open for a long time without further comment. Multiple users confirmed that recent WoR boot works, on various RPi models. Please follow the instructions here: https://www.worproject.ml/guides/how-to-install and here: https://rpi4-uefi.dev/alternate-guide-running-windows-10-on-the-pi-4/. If you still can't get it to work, feel free to re-open or submit a new issue
