### ISSUE TITLE
Unable to start windows on pi4b

### ISSUE THREAD

**Issue by liusitong-91** [pftf/RPi4#169]
I made an EMMC to TF board, but the screen only shows the picture of Respberry PI, and I can't start windows

**Comment by samerhaj** [comment]
This issue does not have enough details. 

Please follow the Windows-on-RPi directions at

- https://rpi4-uefi.dev/alternate-guide-running-windows-10-on-the-pi-4/
and
- https://www.worproject.ml/guides/how-to-install

If you still have issues after following those guides, please open new issue here with details of what you are using and what is not working.

Closing this issue for now, but please feel free to open/create new one if needed.
