### ISSUE TITLE
Change default compilation to disable 3GB RAM limit

### ISSUE THREAD

**Issue by Botspot** [pftf/RPi4#175]
I was talking with the guys on [the Developer-Ecosystem Discord server](https://discord.gg/HhB8kU5rg4) about the possibilities of programmatically changing the UEFI variables to disable the 3GB RAM limit.

There appear to be ways to do it, but the simplest solution would be to simply change the default value while compiling. Have you guys ever considered doing this?

**Comment by frezbo** [comment]
@Botspot do you have any links/docs on how to programmatically change the limit?

**Comment by Botspot** [comment]
> @Botspot do you have any links/docs on how to programmatically change the limit?

No, I'm not aware of a way to run a script from within Windows OS in order to change the limit. But that's not what I'm asking.

I'm asking for the _default_ value of `RamLimitTo3GB` to be changed, so that the UEFI is compiled with this setting already changed.

**Comment by Botspot** [comment]
I would imagine that changing the default value of this setting would be incredibly straightforward.

Most likely it just requires changing the source code in one place.
Below is a search I made in the uefi repository - it may help narrow down what needs to be changed! https://github.com/tianocore/edk2-platforms/search?q=RamLimitTo3GB

**Comment by frezbo** [comment]
@Botspot thanks, from your message I assumed there was a programmatic way to set the limit to greater then 3GB , like a script or something.

**Comment by pbatard** [comment]
Adding `--pcd gRaspberryPiTokenSpaceGuid.PcdRamLimitTo3GB=0` during compilation should do the trick.

You can usually find platform specific options [that are exposed as PCDs in the `.dsc` for the platform](https://github.com/tianocore/edk2-platforms/blob/master/Platform/RaspberryPi/RPi4/RPi4.dsc#L513), along with their default value.

Then, if you want to override an option, you can just add `--pcd <full_name_of_PCD>=<override_value>` when invoking `build`.

**Comment by Gatsby-Lee** [comment]
Now, I understand why it can't be simply updated.
