### ISSUE TITLE
Booting Risc OS, possible?

### ISSUE THREAD

**Issue by vanfanel** [pftf/RPi4#200]
Hi,

Is it theorically possible to boot Risc OS using this UEFI bootloader on the Pi4?

What would a menu entry for it look like?

Thanks!

**Comment by paulwratt** [comment]
It would need to boot with the DeviceTree, but I believe they have a Closed Source Bootloader (eg. their Primary display out is opposite of other OS's), so you probably _wont_ get it to work (unless that situation has changed).

**Comment by pbatard** [comment]
I would think this question is out of scope. The goal of this project is to boot ARM64 based OSes, not RISC. As such I will close this issue.
