### ISSUE TITLE
Status - Making Pi ServerReady

### ISSUE THREAD

**Issue by paulwratt** [pftf/RPi4#207]
It would be useful to at least have Release 1.32 on https://rpi4-uefi.dev/status/ list, even if there is no associated other material.

Is there any estimate on next release?

There has been "some" active discussions of Issues since this release, and RPiOS64 is now Official. The current Buster Image uses Kernel 5.10.63 (as does the Legacy version - verified?). There have been some critical Linux Kernel update since 1.32 was released, and there should be another new RPi Kernel released soon, part of which fixes [a bug with 2 monitors attached](https://github.com/raspberrypi/linux/issues/4888).

**Comment by pbatard** [comment]
I don't think https://rpi4-uefi.dev/status/ is maintained any longer (at least I don't bother to try to update it on new releases, as I don't see the cost/benefit ratio warranting the effort).

And since 1.33 was just released, I will close this issue.
