### ISSUE TITLE
UEFI Firmware defaults to PXE over IPv4

### ISSUE THREAD

**Issue by alsldlflglhljlk** [pftf/RPi4#222]
Even with a compatible UEFI system on another partition, it defaults to PXE over IPv4 and I have to go to the boot manager and select the drive manually.

**Comment by jlinton** [comment]
You can change and save the boot settings if your booting the UEFI firmware from SD. 

See the instructions at the bottom of this issue: https://github.com/pftf/RPi4/issues/151

**Comment by alsldlflglhljlk** [comment]
Apparently, all I needed to do was delete and extract the files to the boot partition. This made it work perfectly.
