### ISSUE TITLE
pi4 hdmi addresses?

### ISSUE THREAD

**Issue by n00b7** [pftf/RPi4#251]
In windows the ACPI Defined Resources for hdmi are shown as:
0xFE807000-0xFE8070FF
0xFE902000-0xFE9025FF
however the new addresses for HDMI on VC6 are here
https://github.com/librerpi/rpi-open-firmware/blob/master/docs/hdmi.md

**Comment by alsldlflglhljlk** [comment]
So, what's your problem exactly?
