### ISSUE TITLE
Memory limit remain after disabling on v1.37

### ISSUE THREAD

**Issue by pieroproietti** [pftf/RPi4#255]
I installed the  last Raspberry Pi 4 UEFI Firmware **v1.37**, I deactivating the 3 GB limit of RAM, from the UEFI menu, this is saved, but the limit persist.

There are problems, someone can confirm? Thanks

![Screenshot_2024-04-15_10-15-42](https://github.com/pftf/RPi4/assets/958613/a9df82f0-8bf8-42a5-a0c8-31c1c18bef6f)

**Comment by pieroproietti** [comment]
This is the UEFI configuration, Limit to 3 GB Memory is disabled and saved.

![disable-memory-limit](https://github.com/pftf/RPi4/assets/958613/57a03f34-de18-458c-814a-5c8d97c32c03)

**Comment by alsldlflglhljlk** [comment]
`free -h` shows a total of `3.7 Gi`, indicating that the measurement is in gibibytes, not gigabytes. 3.7 gibibytes to gigabytes = 3.97284 gigabytes.

**Comment by pieroproietti** [comment]
@alsldlflglhljlk, I have 8GB model, but yes You are right: this is not a problem of 3GB limit. I will check again.
