### ISSUE TITLE
will this work on rpi 5?

### ISSUE THREAD

**Issue by jamieduk** [pftf/RPi4#260]
will this work on rpi 5?

**Comment by pbatard** [comment]
No it won't. Just like downloading the BIOS from one specific PC and trying to flash it on a different PC will not work, trying to use the Raspberry Pi 4 firmware on the Raspberry Pi 5 will not work.

I'm afraid that (from what I can tell) nobody is working on getting a Raspberry Pi 5 firmware formally integrated into EDK2, which means that we cannot provide anything official here. But you can take a look at https://github.com/worproject/rpi5-uefi for unofficial images.
