### ISSUE TITLE
Usb dont work after the bootloader is loaded

### ISSUE THREAD

**Issue by MarcoPower01** [pftf/RPi4#3]
after the bootloader is loaded the usb stop functioning

**Comment by pbatard** [comment]
From the readme:

> This repository contains __EXPERIMENTAL__ installable builds of the official EDK2 Raspberry Pi 4 UEFI firmware.

> Please do not expect the firmware to be fully functional when it comes to supporting your ARM64 OS of choice (or even to support your OS at all if you plan to use Windows), as it is still very much in development stage.

You are most likely trying to boot Windows. This will __NOT__ work past the bootloader.
