### ISSUE TITLE
Remove RPi specific GraphicsConsoleDxe

### ISSUE THREAD

**Issue by samerhaj** [pftf/RPi4#32]
There is no need to carry our own GraphicsConsoleDxe. The version from MdeModulePkg seems to work just fine.

Some historical commits of why the override was needed back then:

https://github.com/andreiw/RaspberryPiPkg/commit/2c8f67508a7e8aa3cdcb2b273017c9c0a507f40e#diff-8fac8267e1fd36706978d0f7198bf681

https://github.com/andreiw/RaspberryPiPkg/commit/765bfd9e7206590c847c1bfc957ddb57602d2f3d

**Comment by andreiw** [comment]
Yes, this can be removed.

**Comment by pbatard** [comment]
I would assert this can be closed now.
