### ISSUE TITLE
Unable to detect USB and keyboard after initial booting.

### ISSUE THREAD

**Issue by jonahliew** [pftf/RPi4#56]
I have tried various of version v1.10 to v1.13 to start up Windows 10 Arm into my Raspberry pi 4. By the time it ask for my location, I can't even select anything on screen as I notice my USB mouse and keyboard is not detected.

**Comment by pbatard** [comment]
Per the README:
> You will NOT be able to use any of the USB-A ports if you try to run Windows. This means that any attempt to boot Windows from a USB drive plugged at the back of your device will crash.
