### ISSUE TITLE
New start*.elf, fixup*.dat and bootcode.bin are required for the latest stable RPi 4B firmware

### ISSUE THREAD

**Issue by ww898** [pftf/RPi4#79]

**Comment by pbatard** [comment]
These will be naturally updated when we release the next firmware as the build script always picks the most recent version:
https://github.com/pftf/RPi4/blob/master/appveyor.yml#L16-L19

Unless you have new information, `bootcode.bin` (which hasn't been updated in one month) is not needed for the Pi 4.

I will therefore close this issue.
