### ISSUE TITLE
Firmware 1.17 has a few issues on RPi 8GB model

### ISSUE THREAD

**Issue by dongwei67** [pftf/RPi4#83]
Found two issues on the 8GB model that do not exist on 4GB model:

1. The "Continue" in the Setup Menu leads to system hang rather then continue to boot
2. When booting to UEFI Shell, the USB key is not automatically discovered. Only the SD card shows up as the only FS. Requires a "connect -r" followed by "map -r" to find the USB Key.

**Comment by samerhaj** [comment]
Closing as duplicate with #97
