### ISSUE TITLE
Support for gpt partition tables

### ISSUE THREAD

**Issue by bzy-080408** [pftf/RPi4#91]
What time to support the gpt partition table？
the Windows10 installer said that the Windows10ARM must install on a gpt partition table

**Comment by pbatard** [comment]
The UEFI firmware already supports GPT (it's in the specs that any UEFI firmware must support that), and the latest Raspberry Pi firmware does support booting from a GPT ESP (though, if you have an old EEPROM, you may need to upgrade it for GPT ESP boot to work).

So there is absolutely nothing for us to do here. GPT is already 100% supported by both the Pi hardware and the UEFI firmware.

If you can't use GPT, then it's either an issue with how you create your media or an issue with the Windows installer. At any rate, this is not something we can do anything about, as this is completely outside of the scope of this project.
